name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'HealthcareFrontend/HealthCareFrontend-Web/**'
      - 'HealthcareFrontend/HealthCareFrontend-Shared/**'

env:
  SERVER_HOST: ishswami.in
  SERVER_USER: ubuntu
  FRONTEND_DEPLOY_PATH: /var/www/healthcare/frontend
  NODE_VERSION: '18.x'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: HealthcareFrontend/HealthCareFrontend-Web

      - name: Create production env file
        run: |
          echo "VITE_API_URL=https://api.ishswami.in" > .env.production
        working-directory: HealthcareFrontend/HealthCareFrontend-Web

      - name: Build
        run: npm run build
        working-directory: HealthcareFrontend/HealthCareFrontend-Web

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Create a new release directory
          ssh -i ~/.ssh/deploy_key ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "mkdir -p ${{ env.FRONTEND_DEPLOY_PATH }}/releases/$(date +%Y%m%d_%H%M%S)"

          # Upload the build
          scp -i ~/.ssh/deploy_key -r HealthcareFrontend/HealthCareFrontend-Web/dist/* ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.FRONTEND_DEPLOY_PATH }}/releases/$(date +%Y%m%d_%H%M%S)

          # Update the current symlink
          ssh -i ~/.ssh/deploy_key ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.FRONTEND_DEPLOY_PATH }} && \
            rm -f current && \
            ln -s releases/$(date +%Y%m%d_%H%M%S) current"

          # Keep only the last 5 releases
          ssh -i ~/.ssh/deploy_key ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.FRONTEND_DEPLOY_PATH }}/releases && \
            ls -1t | tail -n +6 | xargs -r rm -rf"

      - name: Verify deployment
        run: |
          # Check if index.html exists in the new deployment
          ssh -i ~/.ssh/deploy_key ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "test -f ${{ env.FRONTEND_DEPLOY_PATH }}/current/index.html"
